name: dbt_run_on_push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-numeric: '3.9'

      - name: Install dbt
        run: |
          pip install dbt-snowflake
          
      - name: Check dbt version
        run: dbt --version